### PR TITLE
fix(): resolve issue with spaces in paths or file names

### PR DESCRIPTION
**Pull request by snapstreamjoe**
This will fix issues with directory or file names that contain spaces for both nuget and codesign

### CODE REVIEW

**Comment by dlemstra** [comment]
Thanks for the fix. Could you revert the changes in ` dist/index.js`? I will update that file myself.

**Comment by snapstreamjoe** [comment]
@dlemstra will do, give me a few minutes

**Comment by snapstreamjoe** [comment]
@dlemstra Squashed and removed dist/index.js

**Comment by snapstreamjoe** [comment]
@dlemstra I was torn if I should change the logging to show the from and two names in quotes so others do not think it is a spacing issue. I can push that as a different pr or this one if you wish.

**Review by dlemstra — COMMENTED** [review]
Thanks for also improving the documentation.

**Comment by snapstreamjoe** [comment]
@dlemstra Are you going to tag the latest checkin on master as v1.0.1 so it will be the new default?

**Comment by dlemstra** [comment]
Already moved the tag from v1 to the latest commit.

**Pull request merged**
